[general]
static=yes
writeprotect=no

[local]
exten => 1001,1,Dial(PJSIP/1001,30)
exten => 1001,n,Hangup()

exten => 1002,1,Dial(PJSIP/1002,30)
exten => 1002,n,Hangup()

exten => 600,1,Answer()
exten => 600,n,Playback(demo-congrats)
exten => 600,n,Echo()
exten => 600,n,Hangup()
